# Generated by Django 6.0.6 on 2026-06-06 10:09

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_alter_company_company_type_alter_company_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nom')),
                ('cluster', models.CharField(choices=[('main_construction', 'Construction principale'), ('ancillary_construction', 'Construction secondaire'), ('planning_construction', 'Planification et construction'), ('technology_industry', 'Technologie et industrie')], max_length=30, verbose_name='Groupe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Branche',
                'verbose_name_plural': 'Branches',
                'ordering': ('cluster', 'name'),
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExecutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Type d'exécution",
                'verbose_name_plural': "Types d'exécution",
                'ordering': ('name',),
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('canton', models.CharField(blank=True, choices=[('AG', 'Aargau'), ('AI', 'Appenzell Innerrhoden'), ('AR', 'Appenzell Ausserrhoden'), ('BE', 'Bern'), ('BL', 'Basel-Landschaft'), ('BS', 'Basel-Stadt'), ('FR', 'Fribourg'), ('GE', 'Genève'), ('GL', 'Glarus'), ('GR', 'Graubünden'), ('JU', 'Jura'), ('LU', 'Luzern'), ('NE', 'Neuchâtel'), ('NW', 'Nidwalden'), ('OW', 'Obwalden'), ('SG', 'St. Gallen'), ('SH', 'Schaffhausen'), ('SO', 'Solothurn'), ('SZ', 'Schwyz'), ('TG', 'Thurgau'), ('TI', 'Ticino'), ('UR', 'Uri'), ('VD', 'Vaud'), ('VS', 'Valais'), ('ZG', 'Zug'), ('ZH', 'Zürich')], max_length=2, verbose_name='Canton')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Localité')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='NPA')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('application_deadline', models.DateField(blank=True, null=True, verbose_name='Délai de candidature')),
                ('material_offered', models.BooleanField(default=False, verbose_name='Matériel fourni')),
                ('material', models.CharField(blank=True, max_length=255, verbose_name='Matériel')),
                ('project_volume', models.CharField(blank=True, max_length=255, verbose_name='Volume du projet')),
                ('procedure', models.CharField(choices=[('public', 'Public'), ('by_invitation', 'Sur invitation')], default='public', max_length=20, verbose_name='Procédure')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('closed', 'Clôturé'), ('awarded', 'Attribué')], default='draft', max_length=20, verbose_name='Statut')),
                ('branch', models.ManyToManyField(blank=True, related_name='tenders', to='projects.branch', verbose_name='Branches')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenders', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('execution_type', models.ManyToManyField(blank=True, related_name='tenders', to='projects.executiontype', verbose_name="Types d'exécution")),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenders', to='companies.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': "Appel d'offres",
                'verbose_name_plural': "Appels d'offres",
                'ordering': ('-created_at',),
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TenderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='tenders/', verbose_name='Fichier')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Libellé')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.tender', verbose_name="Appel d'offres")),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'ordering': ('-created_at',),
            },
        ),
    ]
