# Generated by Django 6.0.6 on 2026-06-06 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_seed_catalogue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ('name',), 'verbose_name': 'Branche', 'verbose_name_plural': 'Branches'},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='cluster',
        ),
        migrations.AddField(
            model_name='branch',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.branch', verbose_name='parent'),
        ),
    ]
