# Generated by Django 6.0.6 on 2026-06-04 12:41

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Raison sociale')),
                ('company_type', models.CharField(choices=[('client', "Client (entreprise donneuse d'ordre)"), ('subcontractor', 'Sous-traitant')], default='client', max_length=20, verbose_name="Type d'entreprise")),
                ('uid', models.CharField(blank=True, help_text='Identifiant des entreprises suisse (ex: CHE-123.456.789).', max_length=20, verbose_name='Numéro IDE / UID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='NPA')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Localité')),
                ('canton', models.CharField(blank=True, choices=[('AG', 'Aargau'), ('AI', 'Appenzell Innerrhoden'), ('AR', 'Appenzell Ausserrhoden'), ('BE', 'Bern'), ('BL', 'Basel-Landschaft'), ('BS', 'Basel-Stadt'), ('FR', 'Fribourg'), ('GE', 'Genève'), ('GL', 'Glarus'), ('GR', 'Graubünden'), ('JU', 'Jura'), ('LU', 'Luzern'), ('NE', 'Neuchâtel'), ('NW', 'Nidwalden'), ('OW', 'Obwalden'), ('SG', 'St. Gallen'), ('SH', 'Schaffhausen'), ('SO', 'Solothurn'), ('SZ', 'Schwyz'), ('TG', 'Thurgau'), ('TI', 'Ticino'), ('UR', 'Uri'), ('VD', 'Vaud'), ('VS', 'Valais'), ('ZG', 'Zug'), ('ZH', 'Zürich')], max_length=2, verbose_name='Canton')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ('name',),
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
    ]
