# Generated by Django 6.0.6 on 2026-06-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('client', "Client (entreprise donneuse d'ordre)"), ('subcontractor', 'Sous-traitant'), ('both', 'Client et sous-traitant')], default='client', max_length=20, verbose_name="Type d'entreprise"),
        ),
        migrations.AlterField(
            model_name='company',
            name='uid',
            field=models.CharField(blank=True, help_text='Identifiant des entreprises suisse (ex: CHE-123.456.789).', max_length=20, null=True, unique=True, verbose_name='Numéro IDE / UID'),
        ),
    ]
