# Generated by Django 6.0.6 on 2026-06-10 07:30

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('tenders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
            ],
            options={
                'verbose_name': 'Référence',
                'verbose_name_plural': 'Références',
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='references/images/', verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='subcontractors.reference', verbose_name='Référence')),
            ],
            options={
                'verbose_name': 'Image de référence',
                'verbose_name_plural': 'Images de référence',
            },
        ),
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker_count', models.CharField(blank=True, choices=[('1-5', '1 à 5'), ('6-10', '6 à 10'), ('11-25', '11 à 25'), ('26-50', '26 à 50'), ('51-100', '51 à 100'), ('100+', 'Plus de 100')], max_length=10, verbose_name="Nombre d'employés")),
                ('company_age', models.CharField(blank=True, choices=[('under_3', 'Moins de 3 ans'), ('3_10', '3 à 10 ans'), ('over_10', 'Plus de 10 ans')], max_length=10, verbose_name="Ancienneté de l'entreprise")),
                ('accepts_wir', models.BooleanField(default=False, verbose_name='Accepte le WIR')),
                ('introduction', models.TextField(blank=True, verbose_name='Introduction')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='subcontractors/covers/', verbose_name='Photo de couverture')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='subcontractors/profiles/', verbose_name='Photo de profil')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Localisation')),
                ('branch', models.ManyToManyField(blank=True, related_name='subcontractors', to='tenders.branch', verbose_name='Branches')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subcontractor', to='companies.company', verbose_name='Entreprise')),
                ('references', models.ManyToManyField(blank=True, related_name='subcontractors', to='subcontractors.reference', verbose_name='Références')),
            ],
            options={
                'verbose_name': 'Sous-traitant',
                'verbose_name_plural': 'Sous-traitants',
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubcontractorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='subcontractors.subcontractor', verbose_name='Sous-traitant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil sous-traitant',
                'verbose_name_plural': 'Profils sous-traitants',
            },
        ),
    ]
