# Generated by Django 6.0.6 on 2026-06-07 14:41

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subcontractors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('insurance', 'Assurance (obligatoire)'), ('license', 'Licence / autorisation'), ('vat', 'Attestation TVA'), ('other', 'Autre')], max_length=20, verbose_name='Type de document')),
                ('file', models.FileField(upload_to='proof_documents/', verbose_name='Fichier')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="Valide jusqu'au")),
                ('status', models.CharField(choices=[('valid', 'Valide'), ('expired', 'Expiré'), ('review', 'À vérifier')], default='review', max_length=10, verbose_name='Statut')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='subcontractors.subcontractor', verbose_name='Sous-traitant')),
            ],
            options={
                'verbose_name': 'Document justificatif',
                'verbose_name_plural': 'Documents justificatifs',
                'ordering': ('-created_at',),
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
    ]
