# Generated by Django 6.0.6 on 2026-06-07 14:41

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subcontractors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.CharField(choices=[('basic', 'Basique'), ('pro', 'Pro'), ('premium', 'Premium')], max_length=20, verbose_name='Forfait')),
                ('status', models.CharField(choices=[('incomplete', 'Incomplet'), ('trialing', "Période d'essai"), ('active', 'Actif'), ('past_due', 'Impayé'), ('canceled', 'Annulé')], default='incomplete', max_length=20, verbose_name='Statut')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin de la période en cours')),
                ('subcontractor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='subcontractors.subcontractor', verbose_name='Sous-traitant')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
    ]
