# Generated by Django 6.0.6 on 2026-06-06 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_company_type_alter_company_uid'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcontractor',
            name='user',
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='accepts_wir',
            field=models.BooleanField(default=False, verbose_name='Accepte le WIR'),
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='company_age',
            field=models.CharField(blank=True, choices=[('under_3', 'Moins de 3 ans'), ('3_10', '3 à 10 ans'), ('over_10', 'Plus de 10 ans')], max_length=10, verbose_name="Ancienneté de l'entreprise"),
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='references',
            field=models.TextField(blank=True, verbose_name='Références'),
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='worker_count',
            field=models.CharField(blank=True, choices=[('1-5', '1 à 5'), ('6-10', '6 à 10'), ('11-25', '11 à 25'), ('26-50', '26 à 50'), ('51-100', '51 à 100'), ('100+', 'Plus de 100')], max_length=10, verbose_name="Nombre d'employés"),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='Fonction')),
                ('is_company_admin', models.BooleanField(default=False, verbose_name="Administrateur de l'équipe")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_members', to='companies.company', verbose_name='Entreprise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil client',
                'verbose_name_plural': 'Profils clients',
            },
        ),
        migrations.CreateModel(
            name='SubcontractorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='users.subcontractor', verbose_name='Sous-traitant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil sous-traitant',
                'verbose_name_plural': 'Profils sous-traitants',
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
