# Generated by Django 6.0.6 on 2026-06-06 10:09

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0002_remove_subcontractor_user_subcontractor_accepts_wir_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='branch',
            field=models.ManyToManyField(blank=True, related_name='subcontractors', to='projects.branch', verbose_name='Branches'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=apps.users.models.get_language_choices, default='fr', max_length=2, verbose_name='Langue'),
        ),
    ]
