# Generated by Django 6.0.6 on 2026-06-06 15:47

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_role_subcontractor_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Référence',
                'verbose_name_plural': 'Références',
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='subcontractors/covers/', verbose_name='Photo de couverture'),
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='introduction',
            field=models.TextField(blank=True, verbose_name='Introduction'),
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Localisation'),
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='subcontractors/profiles/', verbose_name='Photo de profil'),
        ),
        migrations.RemoveField(
            model_name='subcontractor',
            name='references',
        ),
        migrations.CreateModel(
            name='ReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='references/images/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.reference', verbose_name='Référence')),
            ],
            options={
                'verbose_name': 'Image de référence',
                'verbose_name_plural': 'Images de référence',
            },
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='subcontractors', to='users.reference', verbose_name='Références'),
        ),
    ]
