# Generated by Django 6.0.6 on 2026-06-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_reference_subcontractor_cover_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referenceimage',
            name='caption',
        ),
        migrations.AddField(
            model_name='reference',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='reference',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AddField(
            model_name='referenceimage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
