# Generated by Django 6.0.6 on 2026-06-06 10:09

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_subcontractor_user_subcontractor_accepts_wir_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSubcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sous-traitant favori',
                'verbose_name_plural': 'Sous-traitants favoris',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_letter', models.TextField(blank=True, verbose_name='Message')),
                ('quote_file', models.FileField(blank=True, null=True, upload_to='application_quotes/', verbose_name='Offre / pièce jointe')),
                ('quote_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Montant de l'offre")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée')], default='pending', max_length=10, verbose_name='Statut')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Décidé le')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_applications', to=settings.AUTH_USER_MODEL, verbose_name='Décidé par')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.subcontractor', verbose_name='Sous-traitant')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ('-created_at',),
            },
            bases=(apps.core.models.CRUDUrlMixin, models.Model),
        ),
    ]
