# Generated by Django 6.0.6 on 2026-06-06 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('companies', '0002_alter_company_company_type_alter_company_uid'),
        ('projects', '0001_initial'),
        ('users', '0003_remove_user_role_subcontractor_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.tender', verbose_name="Appel d'offres"),
        ),
        migrations.AddField(
            model_name='favoritesubcontractor',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_subcontractors', to='companies.company', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='favoritesubcontractor',
            name='subcontractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='users.subcontractor', verbose_name='Sous-traitant'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('tender', 'subcontractor'), name='unique_application_per_tender_subcontractor'),
        ),
        migrations.AddConstraint(
            model_name='favoritesubcontractor',
            constraint=models.UniqueConstraint(fields=('company', 'subcontractor'), name='unique_favorite_per_company_subcontractor'),
        ),
    ]
