# Generated by Django 6.0.6 on 2026-06-10 07:30

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='Fonction')),
                ('is_company_admin', models.BooleanField(default=False, verbose_name="Administrateur de l'équipe")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_members', to='companies.company', verbose_name='Entreprise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil client',
                'verbose_name_plural': 'Profils clients',
            },
            bases=(models.Model, apps.core.models.CRUDUrlMixin),
        ),
    ]
